feat: Update prod Dockerfile

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -25,6 +25,10 @@ RUN install-php-extensions \
 # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
+COPY --link .docker/php/app.ini $PHP_INI_DIR/conf.d/
+COPY --link .docker/franken/Caddyfile /etc/caddy/Caddyfile
+COPY --link .docker/supervisor.d/conf.d/messenger-worker.conf /opt/docker/etc/supervisor.d/messenger-worker.conf
+
 HEALTHCHECK --start-period=60s CMD curl -f http://localhost:2019/metrics || exit 1
 CMD ["/usr/bin/supervisord"]
 
@@ -32,3 +36,31 @@ CMD ["/usr/bin/supervisord"]
 FROM frankenphp_base AS frankenphp_dev
 
 RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
+
+# Prod FrankenPHP image
+FROM frankenphp_base AS frankenphp_prod
+
+ENV APP_ENV=prod
+
+RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
+
+COPY --link .docker/php/app.prod.ini $PHP_INI_DIR/conf.d/
+
+# prevent the reinstallation of vendors at every changes in the source code
+COPY --link composer.* symfony.* ./
+RUN set -eux; \
+	composer install --no-cache --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress
+
+# copy sources
+COPY --link . ./
+
+# cleanup
+RUN rm -rf .docker
+RUN rm -rf .github
+
+RUN set -eux; \
+	mkdir -p var/cache var/log; \
+	composer dump-autoload --classmap-authoritative --no-dev; \
+	composer dump-env prod; \
+	composer run-script --no-dev post-install-cmd; \
+	chmod +x bin/console; sync;
